apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: moryacm/computacionparalela:latest
          name: django
          ports:
            - containerPort: 8000
              name: gunicorn
---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
  labels:
    app: django
spec:
  selector:
    app: django
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
